# Generated by Django 4.1.2 on 2022-10-12 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sexo', to='estudiantes.maestra'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_identificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_identificacion', to='estudiantes.maestra'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sexoP', to='estudiantes.maestra'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo_identificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_identificacionP', to='estudiantes.maestra'),
        ),
    ]
