# Generated by Django 4.1.2 on 2022-10-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_maestra_estudiante_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturaxgrupo',
            name='periodo_academico',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupo',
            name='cant_estudiantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maestra',
            name='dependecia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nota',
            name='logro',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota',
            field=models.FloatField(default=0),
        ),
    ]
